### ISSUE TITLE
How to run the speed benchmark over the mixers?

### ISSUE THREAD

**Issue by jonmaiga** [martinus/better-faster-stronger-mixer#1]
Hi Martinus,

I've just published code for a bit mixer ([mx3](https://github.com/jonmaiga/mx3/)) and wanted to see how it does in your test suite. I managed to build it with clang, but unsure how to actually run nanobenchmark over all mixers?

Just starting 'mixer' seems to start 'coverage' and I don't see any benchmark tests in the list of test cases (--ltc), what am I missing?

Best regards, Jon

**Comment by martinus** [comment]
I've pushed an update, it should now run the benchmarks by just running `./mixer`

**Comment by jonmaiga** [comment]
Thank you and wow, the benchmark ran really quickly (and confirmed my own measurements)!

**Comment by martinus** [comment]
awesome :+1:
